services:
  - type: web
    name: btc-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend_api.inference:app --host 0.0.0.0 --port $PORT
    pythonVersion: 3.10.0
    autoDeploy: true
